# Badgetizr Configuration for jjConfig
# Adds dynamic badges to pull requests

badge_wip:
  enabled: "true"
  settings:
    color: "yellow"
    label: "WIP"
    logo: "vlcmediaplayer"
    labelized: "work in progress"

badge_hotfix:
  enabled: "true"
  settings:
    color: "red"
    text_color: "white"
    label: "HOTFIX"
    labelized: "hotfix"

badge_base_branch:
  enabled: "true"
  settings:
    base_branch: "main"
    color: "purple"
    label: "Target"

badge_ci:
  enabled: "true"
  settings:
    label: "CI"
    logo: "githubactions"

badge_dynamic:
  enabled: "true"
  settings:
    patterns:
      - badge_docs:
        sed_pattern: '(docs:|chore\(docs\):)'
        label: "Type"
        value: "Documentation"
        color: "blue"
      - badge_feat:
        sed_pattern: '(feat:|feat\(.*\):)'
        label: "Type"
        value: "Feature"
        color: "green"
      - badge_fix:
        sed_pattern: '(fix:|fix\(.*\):)'
        label: "Type"
        value: "Bugfix"
        color: "orange"
      - badge_security:
        sed_pattern: "(security:|sec:)"
        label: "Type"
        value: "Security"
        color: "red"
      - badge_breaking:
        sed_pattern: "(BREAKING CHANGE|!:)"
        label: "⚠️"
        value: "Breaking"
        color: "red"

badge_ready_for_approval:
  enabled: "true"
  settings:
    color: "darkgreen"
    label: "Ready"
    logo: "checkmarx"
    labelized: "ready for review"
